# Generated by Django 4.1.5 on 2023-01-16 09:10

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cost', models.FloatField()),
                ('yearly_offer', models.CharField(max_length=128)),
                ('is_monthly', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('addons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addon')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.plan')),
            ],
        ),
    ]
