# Generated by Django 4.1.5 on 2023-01-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_form_formdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formdata',
            options={'verbose_name_plural': 'Form Input Data'},
        ),
        migrations.AddField(
            model_name='formdata',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
